blog/urls.py
from django.conf.urls.static import static
from django.conf import settings
from blog import views
from django.urls import path
from django.contrib import admin

app_name = 'Blogs'

urlpatterns = [
#     path('admin/', admin.site.urls),
    path('',views.some,name='all_blogs'),
    path('<int:blog_id>/',views.details,name='details'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('blog/',include('blog.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models

class Blogs(models.Model):
          title=models.CharField(max_length=100)
          date=models.DateField()
          description=models.CharField(max_length=3000)

          def __str__(self):
             return self.title
    

portfolio/models.py
from django.db import models

class Project(models.Model):
          title=models.CharField(max_length=100)
          description=models.CharField(max_length=250)
          img=models.ImageField(upload_to='portfolio/images')
          url=models.URLField(blank=True)

          def __str__(self):
              return self.title
          

blog/views.py
from django.shortcuts import render,get_object_or_404
from . import urls
from .models import Blogs

# Create your views here.
def some(request):
     all_blogs = Blogs.objects.order_by('-date')
     return render (request,'portfo/blog.html', {'myBlogs':all_blogs})


def details(request,blog_id):
     blogs = get_object_or_404(Blogs, pk=blog_id)
     return render(request,'portfo/details.html', {'details':blogs})

portfolio/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Project

def home(request):
     project  = Project.objects.all()
     return render (request,'blog/home.html',  {'projects':project})

blog/templates/portfo/blog.html
{% extends 'blog/base.html' %}

{% block content %}


<h1>Blogs</h1>
<h4>Satya has written {{ myBlogs.count }} blog{{ myBlogs.count|pluralize }} </h4>
<br />
{% for blog in myBlogs %}

<a href="{% url 'Blogs:details' blog.id %}"><h3>{{ blog.title }}</h3></a>
<h4>{{ blog.date|date:'D M Y'|upper }}</h4>
<p>{{ blog.description|safe|truncatechars:100 }}</p>
<br />
<br />
{% endfor %}
{% endblock %}

blog/templates/portfo/details.html
{% extends 'blog/base.html' %}

{% block content %}

<h1 class="text-center mt-5" id="blogdetailtitle">{{ details.title }}</h1>
<h5 class="text-center text-muted mb-5"> ---{{ details.date|date:'F jS Y' }}--- </h5>

{{ details.description|safe }}

{% endblock %}

portfolio/templates/blog/base.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

  <link rel="stylesheet" href="{% static "blog/custom.css" %}">

  <link href="https://fonts.googleapis.com/css?family=Lato&display=swap" rel="stylesheet">

  <link rel="icon" type="image/png" href="{% static "portfolio/yourname.png" %}">

  <title>Satya Govind</title>
</head>

<body>

  <nav id="topNav" class="navbar navbar-expand-md navbar-light">
    <div class="container">
      <a class="navbar-brand" href="{% url 'home' %}">
        <img src="{% static "portfolio/Logo.png" %}" width="30" height="30" class="d-inline-block align-top" alt="">
        <span>Satya Govind</span>
      </a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse text-center" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{% static "portfolio/attachment.pdf" %}">Resume</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://www.linkedin.com/in/m-satyagovind-92a1a31b6/" target="_blank">LinkedIn</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="https://twitter.com/MSatyagovind" target="_blank">Twitter</a>
          </li>
          <li>
            <a role="button" href="{% url 'Blogs:all_blogs' %}" class="btn btn-primary">Blog</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container">
    {% block content %}{% endblock %}
  </div>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

</html>

portfolio/templates/blog/home.html
{% extends 'blog/base.html' %}

{% load static %}

{% block content %}

<div class="row justify-content-center my-3">
  <div class="col-5">
    <img src="{% static 'portfolio/sg.png' %}" class="img-fluid">
  </div>
</div>



<div class="row justify-content-center mb-3">
  <div class="col-md-9 text-center">
    <h1 id="hometext" class="font-weight-bold">Satya Govind is Commander-in-Chief at SG-code and lives in Downtown Tokyo</h1>
  </div>
</div>


<h2 class="mt-5">Portfolio</h2>
<hr>
<div class="row">
  {% for project in projects %}
  <div class="col-lg-4 col-md-6">

    {% if project.url %}
    <a href="{{ project.url }}">
      <img src="{{ project.image.url }}" class="img-fluid mb-2">
    </a>
    {% else %}

    <img src="{{ project.image.url }}" class="img-fluid mb-2">
    {% endif %}
    <h3>{{ project.title }}</h3>
    <p>{{ project.description }}</p>

  </div>
  {% endfor %}
</div>

{% endblock content %}


{% comment %} {% load static %}
<a href={% url 'Blogs:all_blogs' %}> Blogs</a>
<br/>


<a href="{% static 'portfolio/attachment.pdf' %}"> Resume </a>

<img src="{% static 'portfolio/sg.png' %}" height="500" width="850" />

{% for project in projects %}

<h2>{{ project.title }}</h2>
<p>{{ project.description }}</p>
<p>
  <img src="{{ project.img.url }}" height="250" width="350" />
  <br />
  <br />
  {% if project.url %}
  <a href="{{ project.url }}">Link</a>
  {% endif %} {% endfor %}
</p> {% endcomment %}
{% comment %} {% endblock content %} {% endcomment %}